/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projectuas;

import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */

public class dashboardutama extends javax.swing.JFrame {
    panelhalamandashboard a = new panelhalamandashboard();
        panelhalamankatalogmobil b = new panelhalamankatalogmobil();
        panelhalamanpemesanan c = new panelhalamanpemesanan();
        panelhalamanpembayaran d = new panelhalamanpembayaran();
        panelhalamandatamobil e = new panelhalamandatamobil();
        panelhalamandashboardowner f = new panelhalamandashboardowner();
       
        
        private String levelUser;
        
    /**
     * Creates new form dashboardutama
     */
    
 
    public dashboardutama(String level) {
        initComponents();
        this.levelUser = level;   
          setSize(950, 600);
        setLocationRelativeTo(null);
        setMinimumSize(new java.awt.Dimension(1000, 650));
 
        main.add(a);
        main.add(b);
        main.add(c);
        main.add(d);
        main.add(e);
        main.add(f);
 
        b.setParentDashboard(this);
 
        a.setVisible(false);
        b.setVisible(false);
        c.setVisible(false);
        d.setVisible(false);
        e.setVisible(false);
        f.setVisible(false);
 
                main.addComponentListener(new java.awt.event.ComponentAdapter() {
            @Override
            public void componentResized(java.awt.event.ComponentEvent evt) {
                for (java.awt.Component comp : main.getComponents()) {
                    comp.setSize(main.getWidth(), main.getHeight());
                }
            }
        });
         
                aturHakAkses();
         }
          private void aturHakAkses() {
        dashboard.setVisible(false);
        katalogmobil.setVisible(false);
        pemesanan.setVisible(false);
        pembayaran.setVisible(false);
        datamobil.setVisible(false);
        dashboardowner.setVisible(false);
 
        
        logout.setVisible(true);
        
        switch (levelUser) {
            case "Admin":
                dashboard.setVisible(true);
                katalogmobil.setVisible(true);
                pemesanan.setVisible(true);
                pembayaran.setVisible(true);
                datamobil.setVisible(true);
                dashboardowner.setVisible(true);
                tampilPanel(a);
                break;
                
                case "Owner":
                dashboard.setVisible(true);
                katalogmobil.setVisible(true);
                pemesanan.setVisible(true);
                pembayaran.setVisible(true);
                datamobil.setVisible(true);
                dashboardowner.setVisible(true);
                tampilPanel(f);
                break;
                 case "Customer":
                katalogmobil.setVisible(true);
                pemesanan.setVisible(true);
                tampilPanel(b);
                break;
 
            case "Kasir":
                pembayaran.setVisible(true);
                tampilPanel(d);
                break;
          
            default:
                JOptionPane.showMessageDialog(this, "Level tidak dikenali!");
                break;
        }
        
          }
    
    
    public void bookingMobil(String namaMobil) {
    c.refreshData();          
    tampilPanel(c);
    c.setMobilTerpilih(namaMobil);
    }
 
    private void tampilPanel(javax.swing.JPanel panel) {
        a.setVisible(false);
        b.setVisible(false);
        c.setVisible(false);
        d.setVisible(false);
        e.setVisible(false);
        f.setVisible(false);
        panel.setVisible(true);
        
        
    }
 
   
    
    private void proseslogout() {
        int konfirmasi = JOptionPane.showConfirmDialog(
                this,
                "Apakah Anda yakin ingin logout?",
                "Konfirmasi Logout",
                JOptionPane.YES_NO_OPTION);
 
        if (konfirmasi == JOptionPane.YES_OPTION) {
            this.dispose();
            halamanlogin login = new halamanlogin();
            login.setVisible(true);
        }
    }
 
    
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        main = new javax.swing.JLayeredPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        dashboard = new javax.swing.JMenu();
        katalogmobil = new javax.swing.JMenu();
        pemesanan = new javax.swing.JMenu();
        pembayaran = new javax.swing.JMenu();
        datamobil = new javax.swing.JMenu();
        dashboardowner = new javax.swing.JMenu();
        logout = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(47, 164, 215));

        javax.swing.GroupLayout mainLayout = new javax.swing.GroupLayout(main);
        main.setLayout(mainLayout);
        mainLayout.setHorizontalGroup(
            mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 593, Short.MAX_VALUE)
        );
        mainLayout.setVerticalGroup(
            mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 477, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main)
        );

        dashboard.setText("dashboard");
        dashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dashboardMouseClicked(evt);
            }
        });
        jMenuBar1.add(dashboard);

        katalogmobil.setText("katalogmobil");
        katalogmobil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                katalogmobilMouseClicked(evt);
            }
        });
        jMenuBar1.add(katalogmobil);

        pemesanan.setText("pemesanan");
        pemesanan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pemesananMouseClicked(evt);
            }
        });
        jMenuBar1.add(pemesanan);

        pembayaran.setText("pembayaran");
        pembayaran.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pembayaranMouseClicked(evt);
            }
        });
        jMenuBar1.add(pembayaran);

        datamobil.setText("datamobil");
        datamobil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                datamobilMouseClicked(evt);
            }
        });
        jMenuBar1.add(datamobil);

        dashboardowner.setText("dashboardowner");
        dashboardowner.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dashboardownerMouseClicked(evt);
            }
        });
        jMenuBar1.add(dashboardowner);

        logout.setText("logout");
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });
        jMenuBar1.add(logout);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardMouseClicked
        // TODO add your handling code here:
        tampilPanel (a);
    }//GEN-LAST:event_dashboardMouseClicked

    private void katalogmobilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_katalogmobilMouseClicked
        // TODO add your handling code here:
         b.refreshData();
        tampilPanel(b);
       
       
    }//GEN-LAST:event_katalogmobilMouseClicked

    private void pemesananMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pemesananMouseClicked
        // TODO add your handling code here:
        c.refreshData(); 
        tampilPanel (c);
    }//GEN-LAST:event_pemesananMouseClicked

    private void pembayaranMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pembayaranMouseClicked
        // TODO add your handling code here:
        tampilPanel(d);
    }//GEN-LAST:event_pembayaranMouseClicked

    private void datamobilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_datamobilMouseClicked
        // TODO add your handling code here:
        tampilPanel(e);
    }//GEN-LAST:event_datamobilMouseClicked

    private void dashboardownerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardownerMouseClicked
        // TODO add your handling code here:
        tampilPanel(f);
    }//GEN-LAST:event_dashboardownerMouseClicked

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        // TODO add your handling code here:
        proseslogout();
    }//GEN-LAST:event_logoutMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dashboardutama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dashboardutama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dashboardutama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dashboardutama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dashboardutama("Admin").setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu dashboard;
    private javax.swing.JMenu dashboardowner;
    private javax.swing.JMenu datamobil;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu katalogmobil;
    private javax.swing.JMenu logout;
    private javax.swing.JLayeredPane main;
    private javax.swing.JMenu pembayaran;
    private javax.swing.JMenu pemesanan;
    // End of variables declaration//GEN-END:variables
}
